source:
  api_endpoint: http://data.ecan.govt.nz/
  hts: WQLawa2019.hts
  std_factor: 4
  iqr_factor: 4
  mtypes:
    Nitrate-N Nitrite-N:
      min: 0
      max: 30
    Total Nitrogen:
      min: 0
      max: 30
    # Dissolved Inorganic Nitrogen:
    #   min: 0
    #   max: 30
    Ammoniacal Nitrogen:
      min: 0
      max: 10
    Dissolved Reactive Phosphorus:
      min: 0
      max: 2
    Total Phosphorus:
      min: 0
      max: 10
    Turbidity:
      min: 0
      max: 2000
    pH (Field):
      min: 6
      max: 12
    Black Disc Clarity:
      min: 0
      max: 30
    E. coli:
      min: 0
      max: 5000
